name: Build ISO

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: sudo apt install -y xorriso gcc x86_64-elf-gcc x86_64-elf-binutils make
    - name: Build ISO
      run: make
    - name: Upload ISO
      uses: actions/upload-artifact@v3
      with:
        name: novosta-iso
        path: novosta.iso
