name: Build ISO

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld make git xorriso

      - name: Build Novosta ISO
        run: make

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: novosta-iso
          path: novosta.iso
          if-no-files-found: error
